source 'https://cdn.cocoapods.org/'
source 'https://github.com/changjianfeishui/mht-specs'
use_frameworks!

platform :ios, '13.0'

target 'MHTLoginModelInterface_Example' do
  pod 'MHTLoginModelInterface', :path => '../'

  target 'MHTLoginModelInterface_Tests' do
    inherit! :search_paths

    
  end
end
