use_frameworks!

platform :ios, '10.0'

target 'MHTLoginModelInterface_Example' do
  pod 'MHTLoginModelInterface', :path => '../'

  target 'MHTLoginModelInterface_Tests' do
    inherit! :search_paths

    
  end
end
